## Licensed under the terms of http://www.apache.org/licenses/LICENSE-2.0

name: Apache Jena CI
on: [workflow_dispatch, push]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04-ppc64le
            architecture: ppc64le
          - os: ubuntu-latest
            architecture: x64

    steps:
      - uses: actions/checkout@v4

      # Install Maven manually by downloading from the official source
      - name: Install Maven
        run: |
          MAVEN_VERSION=3.9.4
          wget https://archive.apache.org/dist/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz
          tar -xvzf apache-maven-$MAVEN_VERSION-bin.tar.gz
          sudo mv apache-maven-$MAVEN_VERSION /opt/maven
          echo "Maven installed at /opt/maven"

          # Add Maven to the PATH
          echo "export PATH=/opt/maven/bin:$PATH" >> $GITHUB_ENV

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          architecture: ${{ matrix.architecture }}
          distribution: "temurin"
          java-version: "17"

      # Build the project using Maven
      - name: Build with Maven
        run: mvn -B --file pom.xml -Dmaven.javadoc.skip=true install
