## Licensed under the terms of http://www.apache.org/licenses/LICENSE-2.0

name: Apache Jena CI
# Manual
on: [workflow_dispatch, push]

#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04-ppc64le
            architecture: ppc64le
          - os: ubuntu-latest
            architecture: x64

    steps:
      - uses: actions/checkout@v4

      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          architecture: ${{ matrix.architecture }}
          distribution: "temurin"
          java-version: "17"

      - name: Build with Maven
        run: mvn -B --file pom.xml -Dmaven.javadoc.skip=true install
